apiVersion: v1
data:
    UNISKAI_API_KEY: {{ .Values.uniskai.apiKey | b64enc }}
    UNISKAI_ENV_ID: {{ .Values.uniskai.environmentId | b64enc }}
kind: Secret
metadata:
  name: {{ include "controller.fullname" . }}
  namespace: {{ required "namespace is required" .Values.namespace }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}