apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniskai-agent
  namespace: uniskai
  labels:
    app: uniskai-agent
    app.kubernetes.io/name: uniskai-agent
    app.kubernetes.io/version: "0.0.5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uniskai-agent
  template:
    metadata:
      labels:
        app: uniskai-agent
      annotations:
        kubectl.kubernetes.io/default-container: uniskai-agent
    spec:
      serviceAccountName: uniskai-agent
      securityContext:
        {}
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
      volumes:
        - name: vpn-config
          secret:
            secretName: vpn-config
            items:
                - key: client.ovpn
                  path: client.ovpn
        - name: vpn-auth
          secret:
            secretName: vpn-auth
            items:
                - key: auth.txt
                  path: auth.txt
        - name: route-script
          configMap:
            name: route-script
            items:
              - key: route-override.sh
                path: route-override.sh
        - name: tmp
          emptyDir: {}
      initContainers:
        - name: vpn-route-init
          image: busybox
          command: ['/bin/sh', '-c', 'cp /vpn/route-override.sh /tmp/route/route-override.sh; chown root:root /tmp/route/route-override.sh; chmod o+x /tmp/route/route-override.sh;']
          volumeMounts:
            - name: tmp
              mountPath: /tmp/route
            - name: route-script
              mountPath: /vpn/route-override.sh
              subPath: route-override.sh
      containers:
        - name: vpn
          image: dperson/openvpn-client
          command: ["/bin/sh","-c"]
          args: ["openvpn --config 'vpn/client.ovpn' --auth-user-pass 'vpn/auth.txt' --script-security 3 --route-up /tmp/route/route-override.sh;"]
          stdin: true
          tty: true
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: TZ
              value: "Turkey"
          volumeMounts:
            - name: vpn-config
              mountPath: /vpn/client.ovpn
              subPath: client.ovpn
            - name: vpn-auth
              mountPath: /vpn/auth.txt
              subPath: auth.txt
            - name: tmp
              mountPath: /tmp/route
        - name: uniskai-agent
          image: uniskaidevoa.azurecr.io/uniskai-agent:0.0.5
          imagePullPolicy: IfNotPresent
          securityContext:
            {}
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          env:
          - name: RUST_LOG
            value: info,kube=debug,controller=debug
          - name: UNISKAI_API_URL
            value: feature-k8s-cs-agent.profisealabs.com
          envFrom:
            - secretRef:
                name: uniskai-agent
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
