apiVersion: api.profisealabs.com/v1alpha
kind: SchedulePolicy
metadata:
  name: illegal
  labels:
    purpose: example
spec:
  suspend: true
  title: "A schedule policy matching labels"

  namespaceSelector:
    matchLabels:
      provider: kubernetes-sample-apps

  timeZone: "Europe/Kyiv"

  schedule:
    workTimes:
      - start: 07:00:00
        stop: 18:00:00
        days: [Mon, Tue, Wed, Thu, Fri]
