apiVersion: api.profisealabs.com/v1alpha
kind: SchedulePolicy
metadata:
  name: match-labels-schedule-policy
  labels:
    purpose: example
spec:
  suspend: false
  title: "A schedule policy matching labels"

  namespaceSelector:
    matchLabels:
      name: my-namespace

  timeZone: "Europe/Paris"

  schedule:
    workTime:
      start: 07:00:00
      stop: 18:00:00
      repeat: [Mon, Tue, Wed, Thu, Fri]
