apiVersion: api.profisealabs.com/v1alpha
kind: SchedulePolicy
metadata:
  name: illegal
  labels:
    purpose: example
spec:
  suspend: true
  title: "A schedule policy matching labels"

  namespaceSelector:
    matchLabels:
      provider: kubernetes-sample-apps

  timeZone: "Europe/Kyiv"

  assignments:
    - type: work
      from: "2019-01-01T00:00:00Z"
      to: "2019-01-01T23:59:59Z"
      resourceReferences:
        - name: emojivoto

  schedule:      
    workTimes:
      - start: 07:00:00
        stop: 18:00:00
        days: [Mon, Tue, Wed, Thu, Fri]
      - start: 08:00:00
        stop: 09:00:00
        days: [Sat, Sun]
        name: "Weekend"

