apiVersion: api.profisealabs.com/v1alpha
kind: SchedulePolicy
metadata:
  name: example
  labels:
    purpose: example
spec:
  suspend: false
  title: "An example policy"

  namespaceSelector:
    matchLabels:
      provider: kubernetes-sample-apps
    matchNames:
      - bookin.*
      - emojivoto

  timeZone: "Europe/Kyiv"

  assignments:
    - type: work
      from: "2023-09-14T00:00:00Z"
      to: "2023-09-14T22:59:59Z"
      resourceReferences:
        - name: emojivoto
        - name: some-deployment
          namespace: bookinfo
          kind: Deployment
          apiVersion: apps/v1

  schedule:      
    workTimes:
      - start: 07:00:00
        stop: 18:00:00
        days: [Mon, Tue, Wed, Thu, Fri]
      - start: 08:00:00
        stop: 09:00:00
        days: [Sat, Sun]

